### ISSUE TITLE
sortby month

### ISSUE THREAD

**Issue by kfchen02** [jacknap/cosi103Sedan#4]
can someone figure out how to do summarize by month, I am not sure how to extract the month though the SQL date type

**Comment by jacknap** [comment]
added:
return self.run_query("SELECT * FROM transactions WHERE strftime('%m', date)=?", (month,))

in commit 35a2d56

**Comment by jacknap** [comment]
added:
return self.run_query("SELECT * FROM transactions WHERE strftime('%m', date)=?", (month,))

in commit 35a2d56
